services:
  postgres:
    image: postgres:15
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  postgres-user-service:
    image: postgres:15
    container_name: postgres-user-service
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: userdatabase
    ports:
      - "5433:5432"
    volumes:
      - ./user-data:/var/lib/postgresql/data
    networks:
      - my-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: spotify/kafka
    container_name: kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: "kafka"
      ADVERTISED_PORT: 9092
    networks:
      - my-net

  media-service:
    build: ./media-service 
    container_name: media-service
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: mydatabase
      KAFKA_URL: kafka:9092 
      KAFKA_TOPIC: song_uploads 
    command: ["go", "run", "main.go"] 
    networks:
      - my-net

  streaming-service:
    build: ./streaming-service
    container_name: streaming-service
    restart: always
    depends_on:
      media-service:
        condition: service_started
      kafka:
        condition: service_started
    ports:
      - "8080:8080"
    command: ["go", "run", "main.go"] 
    networks:
      - my-net

  search-service:
    build: ./search-service
    container_name: search-service
    restart: always
    depends_on:
      media-service:
        condition: service_started
      kafka:
        condition: service_started
    ports:
      - "8085:8085"
    command: ["go", "run", "main.go"]
    environment:
      KAFKA_URL: kafka:9092 
      KAFKA_TOPIC: song_uploads 
    networks:
      - my-net
      
  user-service:
    build: ./user-service
    container_name: user-service
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      postgres-user-service:
        condition: service_healthy
      media-service:
        condition: service_started
    ports:
      - "8133:8133"
    environment:
      DB_HOST: postgres-user-service
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: userdatabase
    networks:
      - my-net

  gateway-service:
    build: ./gateway
    container_name: gateway-service
    restart: always
    depends_on:
      media-service:
        condition: service_started
      streaming-service:
        condition: service_started
      search-service:
        condition: service_started
      user-service:
        condition: service_started
    ports:
      - "9000:9000"
    environment:
      PORT: 9000
      STREAMING_SERVICE_URL: "http://streaming-service:8080"
      MEDIA_SERVICE_URL: "http://media-service:3000"
      SEARCH_SERVICE_URL: "http://search-service:8085"
      USER_SERVICE_URL: "http://user-service:8133"
    networks:
      - my-net
      
volumes:
  pg_data:
  pg_data_user_service:
  kafka_data:

networks:
  my-net:
    driver: bridge
