spring:
  cloud:
    gateway:
      routes:
        - id: stream-song-route
          uri: ${STREAMING_SERVICE_URL:http://default-streaming-service-url}
          predicates:
            - Path=/api/v1/stream/**
          filters:
            - RewritePath=/api/v1/stream/(?<songId>.*), /v1/stream/${songId}

        - id: songs-route
          uri: ${MEDIA_SERVICE_URL:http://default-media-service-url}
          predicates:
            - Path=/api/v1/songs
          filters:
            - RewritePath=/api/v1/songs, /songs

        - id: artists-route
          uri: ${MEDIA_SERVICE_URL:http://default-media-service-url}
          predicates:
            - Path=/api/v1/artists
            - Method=POST
          filters:
            - RewritePath=/api/v1/artists, /artists

        - id: search-songs-route
          uri: ${SEARCH_SERVICE_URL:http://default-search-service-url}
          predicates:
            - Path=/api/v1/search/songs/**
          filters:
            - RewritePath=/api/v1/search/songs/(?<query>.*), /search/songs/${query}

server:
  port: ${PORT:9000} # Read the port value from the PORT environment variable, default to 9000 if not set

logging:
  level:
    org.springframework.cloud.gateway: TRACE

security:
  jwt:
    public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlEiAGZRoxDR0awaEMcua1JQiPEvznXTM8frHAJlKzHyOxReqWFSD/NebwCUUTkD/tpOquamwATXQtIzUpsNv69WWcIrUx8F3BtA7VquhDPbFmHabrEDdUxq3sfVg7R5Dw/AvdhXIH7wuNwfiy+KzfQSwWtdNZvoKrwMYnovN1l48QQ14VBlUYtsGKszmSgHIFp8uwcGmhwoTyqtIQIVO3ynpOwC5Mr5fEcybGkVZI3ua3uvP7epPLK1FbOCv4tYq8s3YBEoV7x1buBSl8isJUonE7jOoEciDSgFymipmgejDWlktFSns4z0imX4MerK6xPZwTz+LMSQbMbEBYaCHGwIDAQAB"