info:
  contact: {}
  title: Streaming Service API
paths:
  /v1/stream/{songId}:
    get:
      description: Stream a song to the user by providing the song ID
      operationId: streamSongToUser
      parameters:
      - description: Song ID to stream
        in: path
        name: songId
        required: true
        type: integer
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: 'Bad Request: Invalid ID'
          schema:
            type: string
        "500":
          description: 'Internal Server Error: File download failed'
          schema:
            type: string
      summary: Stream a song to user
      tags:
      - StreamHandler
swagger: "2.0"
